### PR TITLE
Node 25 released and add "using bound function" sub test case

### LINKED ISSUE #1994: Add `Symbol.asyncDispose` bound function bug (`TypeError: Symbol(Symbol.asyncDispose) is not a function`)
The following code errors with `TypeError: Symbol(Symbol.asyncDispose) is not a function` on v8 13.6.233.10-node.28 (Node 24.10.0), but passes with v8 14.1.146.11 (Chrome 141.0.7390.70). I guess there was a bug between these versions. I haven't found a bug report in chromium's issue tracker though.
```js
{
	async function close() {
		console.log('called')
	}
	await using n = {
		[Symbol.asyncDispose]: close.bind(null)
	};
}
```
I'm not sure if it's better to add this case in the table, but thought to report this anyways.

### PR DESCRIPTION
**Pull request by sapphi-red**
This PR adds the subtest. This fails with Node 24.11. ~~I didn't add any `res` entry as I wasn't sure how that should be tested.~~ added node 24 & 25 results

https://nodejs.org/ja/blog/release/v25.0.0

fixes #1994

### CODE REVIEW

**Comment by ljharb** [comment]
If it fails on a version of node with manual testing, please do add the entry reflecting it :-)

**Comment by sapphi-red** [comment]
I've added the results. I also added node 25 as that passed the test. Please let me know if I should split the PR into two.

**Review by nicolo-ribaudo — COMMENTED** [review]
This passes in Firefox 147

**Review by ljharb — APPROVED** [review]

File: data-esnext.js [hunk 1]
```diff
@@ -1243,6 +1243,28 @@ exports.tests = [
...
+          disposed = true;
+        }
+        {
+          using _ = resource;
+        }
+        return disposed;
+      */},
+      res: {
+        chrome143: true,
+        firefox147: true,
```
Comment (JLHwung) [inline data-esnext.js:1263]: I can confirm that firefox 141, the first version with unflagged ERM support, is not affected by this bug. I will update the compat-data later today.
